# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190520_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userId',
        ),
    ]
